name          'opentable-homes'
version       '0.2.1'
source        'git://github.com/opentable/puppet-homes.git'
author        'opentable'
summary       'Module for managing local users and ssh keys'
description   'Create local system users and manage their public/private ssh keys'
project_page 'https://github.com/opentable/puppet-homes'
license       'MIT'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'opentable/altlib', '>=0.2.0'